name: Swift

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: SwiftLint
    - uses: norio-nomura/action-swiftlint@3.2.1

